name: Hello GitHub Actions

on:
  push: branch[main]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Print date and time
        run: date

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: echo "Branch: $BRANCH_NAME"

      - name: List files
        run: ls -la

      - name: Runner OS
        run: uname -a
        

